import { createServerFn } from "@tanstack/react-start";
import { scoreFinancialConditions, type FinancialConditionsScore } from "@/lib/scoring/financial-conditions.server";

export interface LiquidityEnginePayload { score: FinancialConditionsScore; indicators: Array<{ concept: string; label: string; series: string; frequency: string; latest: number | null; date: string | null; change1m: number | null; history: Array<{ date: string; value: number }> }>; note: string }
const META: Record<string, { label: string; family: "rates" | "credit" | "liquidity"; higherIsTighter: boolean; weight: number }> = {
  fed_funds:{label:"Federal funds rate",family:"rates",higherIsTighter:true,weight:.15}, treasury_2y:{label:"2Y Treasury yield",family:"rates",higherIsTighter:true,weight:.10}, treasury_10y:{label:"10Y Treasury yield",family:"rates",higherIsTighter:true,weight:.05}, yield_curve_10y2y:{label:"10Y–2Y curve",family:"rates",higherIsTighter:false,weight:.10}, bbb_credit_spread:{label:"BBB credit spread",family:"credit",higherIsTighter:true,weight:.15}, high_yield_spread:{label:"High-yield spread",family:"credit",higherIsTighter:true,weight:.20}, financial_stress:{label:"St. Louis Fed stress",family:"credit",higherIsTighter:true,weight:.15}, broad_money_m2:{label:"M2 money stock",family:"liquidity",higherIsTighter:false,weight:.03}, bank_credit:{label:"Bank credit",family:"liquidity",higherIsTighter:false,weight:.04}, reserve_balances:{label:"Reserve balances",family:"liquidity",higherIsTighter:false,weight:.03},
};
export const getLiquidityEngine = createServerFn({ method: "GET" }).handler(async (): Promise<LiquidityEnginePayload> => {
 const { supabaseAdmin } = await import("@/integrations/supabase/client.server"); const { data: region } = await supabaseAdmin.from("regions").select("id").eq("code","US").maybeSingle(); if (!region) throw new Error("US region missing");
 const { data: registry } = await supabaseAdmin.from("indicator_registry").select("id,concept_code,series_code_native,frequency").eq("region_id",region.id).eq("engine","liquidity").eq("is_active",true).order("concept_code"); const ids=(registry??[]).map((x)=>x.id as string);
 const byId=new Map<string, Array<{date:string;value:number}>>(); if(ids.length){ const {data: rows}=await supabaseAdmin.from("raw_observations").select("indicator_id,observation_date,value_raw,retrieved_at").in("indicator_id",ids).order("observation_date",{ascending:true}).order("retrieved_at",{ascending:true}); for(const row of rows??[]){if(row.value_raw==null)continue;const id=row.indicator_id as string, date=(row.observation_date as string).slice(0,10), a=byId.get(id)??[];const last=a.at(-1);if(last?.date===date)last.value=Number(row.value_raw);else a.push({date,value:Number(row.value_raw)});byId.set(id,a);} }
 const indicators=(registry??[]).map((r)=>{const history=byId.get(r.id as string)??[];const latest=history.at(-1)??null, prior=history.at(-2)??null, meta=META[r.concept_code as string];return {concept:r.concept_code as string,label:meta?.label??r.concept_code as string,series:r.series_code_native as string,frequency:r.frequency as string,latest:latest?.value??null,date:latest?.date??null,change1m:latest&&prior?latest.value-prior.value:null,history};});
 const score=scoreFinancialConditions(indicators.filter((x)=>META[x.concept]).map((x)=>({...META[x.concept],key:x.concept,values:x.history.map((p)=>p.value),current:x.latest})));
 return {score,indicators,note:"Stage 3 uses a transparent, direction-adjusted z-score composite. It is a financial-conditions monitor, not a credit forecast or a validated PCA factor."};
});
