import { createFileRoute } from "@tanstack/react-router";
import { useQuery } from "@tanstack/react-query";
import { useServerFn } from "@tanstack/react-start";
import { AppShell } from "@/components/layout/AppShell";
import { SectionHeader } from "@/components/layout/SectionHeader";
import { getLiquidityEngine } from "@/lib/panels/liquidity.functions";
export const Route=createFileRoute("/_authenticated/macro/liquidity")({head:()=>({meta:[{title:"US Liquidity & Financial Conditions — Research Terminal"}]}),component:LiquidityEngine});
function LiquidityEngine(){const load=useServerFn(getLiquidityEngine);const {data,error,isLoading}=useQuery({queryKey:["liquidity-engine"],queryFn:()=>load(),refetchOnWindowFocus:false});return <AppShell><SectionHeader code="MA · Stage 3 · US Liquidity" title="How restrictive are US financial conditions?" purpose="Rates, curve shape, credit spreads, stress and liquidity aggregates in one transparent monitor." />{isLoading&&<div className="text-xs text-muted-foreground">Loading liquidity engine…</div>}{error&&<div className="text-xs text-[var(--negative)]">Failed to load: {(error as Error).message}</div>}{data&&<><div className="mb-4 grid gap-3 md:grid-cols-4"><Card label="Financial conditions" value={data.score.score?.toFixed(2)??"—"} sub={data.score.regime}/><Card label="Coverage" value={`${data.score.confidence}%`} sub="configured component weight"/><Card label="Method" value="Transparent FCI" sub={data.score.methodology}/><Card label="Interpretation" value={data.score.score!=null&&data.score.score>0?"Tighter than normal":"Easier than normal"} sub="positive score = tighter"/></div><div className="mb-4 rounded border border-border bg-card p-3"><div className="mb-2 font-mono text-[10px] uppercase tracking-wider text-muted-foreground">Contribution ledger</div>{data.score.components.map(c=><div key={c.key} className="grid grid-cols-[1fr_auto_auto] gap-3 border-b border-border/50 py-2 text-xs last:border-0"><span>{c.label}</span><span className="font-mono text-muted-foreground">z {c.zScore?.toFixed(2)??"—"} · {(c.weight*100).toFixed(0)}%</span><span className="font-mono">{c.contribution?.toFixed(2)??"—"}</span></div>)}</div><div className="grid gap-3 md:grid-cols-2 xl:grid-cols-3">{data.indicators.map(i=><div key={i.concept} className="rounded border border-border bg-card p-3"><div className="font-mono text-[10px] text-muted-foreground">{i.series} · {i.frequency}</div><div className="text-sm font-semibold">{i.label}</div><div className="mt-2 text-xl font-semibold">{i.latest?.toLocaleString(undefined,{maximumFractionDigits:2})??"—"}</div><div className="text-[11px] text-muted-foreground">{i.date??"—"} · latest change {i.change1m?.toFixed(2)??"—"}</div></div>)}</div><p className="mt-4 text-[11px] text-muted-foreground">{data.note}</p></>}</AppShell>}
function Card({label,value,sub}:{label:string;value:string;sub:string}){return <div className="rounded border border-border bg-card p-3"><div className="font-mono text-[10px] uppercase text-muted-foreground">{label}</div><div className="mt-1 text-xl font-semibold">{value}</div><div className="text-[11px] capitalize text-muted-foreground">{sub}</div></div>}
