/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as AuthenticatedIndexRouteImport } from './routes/_authenticated/index'
import { Route as AuthenticatedUndervaluationRouteImport } from './routes/_authenticated/undervaluation'
import { Route as AuthenticatedScreenersRouteImport } from './routes/_authenticated/screeners'
import { Route as AuthenticatedRadarRouteImport } from './routes/_authenticated/radar'
import { Route as AuthenticatedOvervaluationRouteImport } from './routes/_authenticated/overvaluation'
import { Route as AuthenticatedMacroRouteImport } from './routes/_authenticated/macro'
import { Route as AuthenticatedHistoryRouteImport } from './routes/_authenticated/history'
import { Route as AuthenticatedDataHealthRouteImport } from './routes/_authenticated/data-health'
import { Route as AuthenticatedAltDataRouteImport } from './routes/_authenticated/alt-data'
import { Route as AuthenticatedAlertsRouteImport } from './routes/_authenticated/alerts'
import { Route as AuthenticatedSecurityIndexRouteImport } from './routes/_authenticated/security.index'
import { Route as AuthenticatedSecuritySymbolRouteImport } from './routes/_authenticated/security.$symbol'
import { Route as AuthenticatedMacroGrowthRouteImport } from './routes/_authenticated/macro.growth'
import { Route as AuthenticatedMacroSplatRouteImport } from './routes/_authenticated/macro.$'
import { Route as AuthenticatedHistoryEventIdRouteImport } from './routes/_authenticated/history.$eventId'
import { Route as AuthenticatedHistorySplatRouteImport } from './routes/_authenticated/history.$'
import { Route as AuthenticatedAltDataSplatRouteImport } from './routes/_authenticated/alt-data.$'
import { Route as ApiPublicVerifyRunRouteImport } from './routes/api/public/verify/run'
import { Route as ApiPublicScoresRunRouteImport } from './routes/api/public/scores/run'
import { Route as ApiPublicProvidersPingRouteImport } from './routes/api/public/providers/ping'
import { Route as ApiPublicIngestUsGrowthFredRouteImport } from './routes/api/public/ingest/us-growth-fred'
import { Route as ApiPublicIngestStooqRouteImport } from './routes/api/public/ingest/stooq'
import { Route as ApiPublicIngestMacroNativeRouteImport } from './routes/api/public/ingest/macro-native'
import { Route as ApiPublicIngestFundamentalsRouteImport } from './routes/api/public/ingest/fundamentals'
import { Route as ApiPublicIngestFredRouteImport } from './routes/api/public/ingest/fred'
import { Route as ApiPublicIngestCommoditiesRouteImport } from './routes/api/public/ingest/commodities'
import { Route as ApiPublicIngestAltdataRouteImport } from './routes/api/public/ingest/altdata'
import { Route as ApiPublicHistoryVerifyNarrativesRouteImport } from './routes/api/public/history/verify-narratives'
import { Route as ApiPublicRadarsUndervaluationRefreshRouteImport } from './routes/api/public/radars/undervaluation/refresh'

const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedIndexRoute = AuthenticatedIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedUndervaluationRoute =
  AuthenticatedUndervaluationRouteImport.update({
    id: '/undervaluation',
    path: '/undervaluation',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedScreenersRoute = AuthenticatedScreenersRouteImport.update({
  id: '/screeners',
  path: '/screeners',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedRadarRoute = AuthenticatedRadarRouteImport.update({
  id: '/radar',
  path: '/radar',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedOvervaluationRoute =
  AuthenticatedOvervaluationRouteImport.update({
    id: '/overvaluation',
    path: '/overvaluation',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedMacroRoute = AuthenticatedMacroRouteImport.update({
  id: '/macro',
  path: '/macro',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedHistoryRoute = AuthenticatedHistoryRouteImport.update({
  id: '/history',
  path: '/history',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedDataHealthRoute = AuthenticatedDataHealthRouteImport.update({
  id: '/data-health',
  path: '/data-health',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAltDataRoute = AuthenticatedAltDataRouteImport.update({
  id: '/alt-data',
  path: '/alt-data',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAlertsRoute = AuthenticatedAlertsRouteImport.update({
  id: '/alerts',
  path: '/alerts',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedSecurityIndexRoute =
  AuthenticatedSecurityIndexRouteImport.update({
    id: '/security/',
    path: '/security/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedSecuritySymbolRoute =
  AuthenticatedSecuritySymbolRouteImport.update({
    id: '/security/$symbol',
    path: '/security/$symbol',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedMacroGrowthRoute =
  AuthenticatedMacroGrowthRouteImport.update({
    id: '/growth',
    path: '/growth',
    getParentRoute: () => AuthenticatedMacroRoute,
  } as any)
const AuthenticatedMacroSplatRoute = AuthenticatedMacroSplatRouteImport.update({
  id: '/$',
  path: '/$',
  getParentRoute: () => AuthenticatedMacroRoute,
} as any)
const AuthenticatedHistoryEventIdRoute =
  AuthenticatedHistoryEventIdRouteImport.update({
    id: '/$eventId',
    path: '/$eventId',
    getParentRoute: () => AuthenticatedHistoryRoute,
  } as any)
const AuthenticatedHistorySplatRoute =
  AuthenticatedHistorySplatRouteImport.update({
    id: '/$',
    path: '/$',
    getParentRoute: () => AuthenticatedHistoryRoute,
  } as any)
const AuthenticatedAltDataSplatRoute =
  AuthenticatedAltDataSplatRouteImport.update({
    id: '/$',
    path: '/$',
    getParentRoute: () => AuthenticatedAltDataRoute,
  } as any)
const ApiPublicVerifyRunRoute = ApiPublicVerifyRunRouteImport.update({
  id: '/api/public/verify/run',
  path: '/api/public/verify/run',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicScoresRunRoute = ApiPublicScoresRunRouteImport.update({
  id: '/api/public/scores/run',
  path: '/api/public/scores/run',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicProvidersPingRoute = ApiPublicProvidersPingRouteImport.update({
  id: '/api/public/providers/ping',
  path: '/api/public/providers/ping',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicIngestUsGrowthFredRoute =
  ApiPublicIngestUsGrowthFredRouteImport.update({
    id: '/api/public/ingest/us-growth-fred',
    path: '/api/public/ingest/us-growth-fred',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicIngestStooqRoute = ApiPublicIngestStooqRouteImport.update({
  id: '/api/public/ingest/stooq',
  path: '/api/public/ingest/stooq',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicIngestMacroNativeRoute =
  ApiPublicIngestMacroNativeRouteImport.update({
    id: '/api/public/ingest/macro-native',
    path: '/api/public/ingest/macro-native',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicIngestFundamentalsRoute =
  ApiPublicIngestFundamentalsRouteImport.update({
    id: '/api/public/ingest/fundamentals',
    path: '/api/public/ingest/fundamentals',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicIngestFredRoute = ApiPublicIngestFredRouteImport.update({
  id: '/api/public/ingest/fred',
  path: '/api/public/ingest/fred',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicIngestCommoditiesRoute =
  ApiPublicIngestCommoditiesRouteImport.update({
    id: '/api/public/ingest/commodities',
    path: '/api/public/ingest/commodities',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicIngestAltdataRoute = ApiPublicIngestAltdataRouteImport.update({
  id: '/api/public/ingest/altdata',
  path: '/api/public/ingest/altdata',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicHistoryVerifyNarrativesRoute =
  ApiPublicHistoryVerifyNarrativesRouteImport.update({
    id: '/api/public/history/verify-narratives',
    path: '/api/public/history/verify-narratives',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicRadarsUndervaluationRefreshRoute =
  ApiPublicRadarsUndervaluationRefreshRouteImport.update({
    id: '/api/public/radars/undervaluation/refresh',
    path: '/api/public/radars/undervaluation/refresh',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof AuthenticatedIndexRoute
  '/auth': typeof AuthRoute
  '/alerts': typeof AuthenticatedAlertsRoute
  '/alt-data': typeof AuthenticatedAltDataRouteWithChildren
  '/data-health': typeof AuthenticatedDataHealthRoute
  '/history': typeof AuthenticatedHistoryRouteWithChildren
  '/macro': typeof AuthenticatedMacroRouteWithChildren
  '/overvaluation': typeof AuthenticatedOvervaluationRoute
  '/radar': typeof AuthenticatedRadarRoute
  '/screeners': typeof AuthenticatedScreenersRoute
  '/undervaluation': typeof AuthenticatedUndervaluationRoute
  '/alt-data/$': typeof AuthenticatedAltDataSplatRoute
  '/history/$': typeof AuthenticatedHistorySplatRoute
  '/history/$eventId': typeof AuthenticatedHistoryEventIdRoute
  '/macro/$': typeof AuthenticatedMacroSplatRoute
  '/macro/growth': typeof AuthenticatedMacroGrowthRoute
  '/security/$symbol': typeof AuthenticatedSecuritySymbolRoute
  '/security/': typeof AuthenticatedSecurityIndexRoute
  '/api/public/history/verify-narratives': typeof ApiPublicHistoryVerifyNarrativesRoute
  '/api/public/ingest/altdata': typeof ApiPublicIngestAltdataRoute
  '/api/public/ingest/commodities': typeof ApiPublicIngestCommoditiesRoute
  '/api/public/ingest/fred': typeof ApiPublicIngestFredRoute
  '/api/public/ingest/fundamentals': typeof ApiPublicIngestFundamentalsRoute
  '/api/public/ingest/macro-native': typeof ApiPublicIngestMacroNativeRoute
  '/api/public/ingest/stooq': typeof ApiPublicIngestStooqRoute
  '/api/public/ingest/us-growth-fred': typeof ApiPublicIngestUsGrowthFredRoute
  '/api/public/providers/ping': typeof ApiPublicProvidersPingRoute
  '/api/public/scores/run': typeof ApiPublicScoresRunRoute
  '/api/public/verify/run': typeof ApiPublicVerifyRunRoute
  '/api/public/radars/undervaluation/refresh': typeof ApiPublicRadarsUndervaluationRefreshRoute
}
export interface FileRoutesByTo {
  '/auth': typeof AuthRoute
  '/alerts': typeof AuthenticatedAlertsRoute
  '/alt-data': typeof AuthenticatedAltDataRouteWithChildren
  '/data-health': typeof AuthenticatedDataHealthRoute
  '/history': typeof AuthenticatedHistoryRouteWithChildren
  '/macro': typeof AuthenticatedMacroRouteWithChildren
  '/overvaluation': typeof AuthenticatedOvervaluationRoute
  '/radar': typeof AuthenticatedRadarRoute
  '/screeners': typeof AuthenticatedScreenersRoute
  '/undervaluation': typeof AuthenticatedUndervaluationRoute
  '/': typeof AuthenticatedIndexRoute
  '/alt-data/$': typeof AuthenticatedAltDataSplatRoute
  '/history/$': typeof AuthenticatedHistorySplatRoute
  '/history/$eventId': typeof AuthenticatedHistoryEventIdRoute
  '/macro/$': typeof AuthenticatedMacroSplatRoute
  '/macro/growth': typeof AuthenticatedMacroGrowthRoute
  '/security/$symbol': typeof AuthenticatedSecuritySymbolRoute
  '/security': typeof AuthenticatedSecurityIndexRoute
  '/api/public/history/verify-narratives': typeof ApiPublicHistoryVerifyNarrativesRoute
  '/api/public/ingest/altdata': typeof ApiPublicIngestAltdataRoute
  '/api/public/ingest/commodities': typeof ApiPublicIngestCommoditiesRoute
  '/api/public/ingest/fred': typeof ApiPublicIngestFredRoute
  '/api/public/ingest/fundamentals': typeof ApiPublicIngestFundamentalsRoute
  '/api/public/ingest/macro-native': typeof ApiPublicIngestMacroNativeRoute
  '/api/public/ingest/stooq': typeof ApiPublicIngestStooqRoute
  '/api/public/ingest/us-growth-fred': typeof ApiPublicIngestUsGrowthFredRoute
  '/api/public/providers/ping': typeof ApiPublicProvidersPingRoute
  '/api/public/scores/run': typeof ApiPublicScoresRunRoute
  '/api/public/verify/run': typeof ApiPublicVerifyRunRoute
  '/api/public/radars/undervaluation/refresh': typeof ApiPublicRadarsUndervaluationRefreshRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/_authenticated/alerts': typeof AuthenticatedAlertsRoute
  '/_authenticated/alt-data': typeof AuthenticatedAltDataRouteWithChildren
  '/_authenticated/data-health': typeof AuthenticatedDataHealthRoute
  '/_authenticated/history': typeof AuthenticatedHistoryRouteWithChildren
  '/_authenticated/macro': typeof AuthenticatedMacroRouteWithChildren
  '/_authenticated/overvaluation': typeof AuthenticatedOvervaluationRoute
  '/_authenticated/radar': typeof AuthenticatedRadarRoute
  '/_authenticated/screeners': typeof AuthenticatedScreenersRoute
  '/_authenticated/undervaluation': typeof AuthenticatedUndervaluationRoute
  '/_authenticated/': typeof AuthenticatedIndexRoute
  '/_authenticated/alt-data/$': typeof AuthenticatedAltDataSplatRoute
  '/_authenticated/history/$': typeof AuthenticatedHistorySplatRoute
  '/_authenticated/history/$eventId': typeof AuthenticatedHistoryEventIdRoute
  '/_authenticated/macro/$': typeof AuthenticatedMacroSplatRoute
  '/_authenticated/macro/growth': typeof AuthenticatedMacroGrowthRoute
  '/_authenticated/security/$symbol': typeof AuthenticatedSecuritySymbolRoute
  '/_authenticated/security/': typeof AuthenticatedSecurityIndexRoute
  '/api/public/history/verify-narratives': typeof ApiPublicHistoryVerifyNarrativesRoute
  '/api/public/ingest/altdata': typeof ApiPublicIngestAltdataRoute
  '/api/public/ingest/commodities': typeof ApiPublicIngestCommoditiesRoute
  '/api/public/ingest/fred': typeof ApiPublicIngestFredRoute
  '/api/public/ingest/fundamentals': typeof ApiPublicIngestFundamentalsRoute
  '/api/public/ingest/macro-native': typeof ApiPublicIngestMacroNativeRoute
  '/api/public/ingest/stooq': typeof ApiPublicIngestStooqRoute
  '/api/public/ingest/us-growth-fred': typeof ApiPublicIngestUsGrowthFredRoute
  '/api/public/providers/ping': typeof ApiPublicProvidersPingRoute
  '/api/public/scores/run': typeof ApiPublicScoresRunRoute
  '/api/public/verify/run': typeof ApiPublicVerifyRunRoute
  '/api/public/radars/undervaluation/refresh': typeof ApiPublicRadarsUndervaluationRefreshRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/alerts'
    | '/alt-data'
    | '/data-health'
    | '/history'
    | '/macro'
    | '/overvaluation'
    | '/radar'
    | '/screeners'
    | '/undervaluation'
    | '/alt-data/$'
    | '/history/$'
    | '/history/$eventId'
    | '/macro/$'
    | '/macro/growth'
    | '/security/$symbol'
    | '/security/'
    | '/api/public/history/verify-narratives'
    | '/api/public/ingest/altdata'
    | '/api/public/ingest/commodities'
    | '/api/public/ingest/fred'
    | '/api/public/ingest/fundamentals'
    | '/api/public/ingest/macro-native'
    | '/api/public/ingest/stooq'
    | '/api/public/ingest/us-growth-fred'
    | '/api/public/providers/ping'
    | '/api/public/scores/run'
    | '/api/public/verify/run'
    | '/api/public/radars/undervaluation/refresh'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/auth'
    | '/alerts'
    | '/alt-data'
    | '/data-health'
    | '/history'
    | '/macro'
    | '/overvaluation'
    | '/radar'
    | '/screeners'
    | '/undervaluation'
    | '/'
    | '/alt-data/$'
    | '/history/$'
    | '/history/$eventId'
    | '/macro/$'
    | '/macro/growth'
    | '/security/$symbol'
    | '/security'
    | '/api/public/history/verify-narratives'
    | '/api/public/ingest/altdata'
    | '/api/public/ingest/commodities'
    | '/api/public/ingest/fred'
    | '/api/public/ingest/fundamentals'
    | '/api/public/ingest/macro-native'
    | '/api/public/ingest/stooq'
    | '/api/public/ingest/us-growth-fred'
    | '/api/public/providers/ping'
    | '/api/public/scores/run'
    | '/api/public/verify/run'
    | '/api/public/radars/undervaluation/refresh'
  id:
    | '__root__'
    | '/_authenticated'
    | '/auth'
    | '/_authenticated/alerts'
    | '/_authenticated/alt-data'
    | '/_authenticated/data-health'
    | '/_authenticated/history'
    | '/_authenticated/macro'
    | '/_authenticated/overvaluation'
    | '/_authenticated/radar'
    | '/_authenticated/screeners'
    | '/_authenticated/undervaluation'
    | '/_authenticated/'
    | '/_authenticated/alt-data/$'
    | '/_authenticated/history/$'
    | '/_authenticated/history/$eventId'
    | '/_authenticated/macro/$'
    | '/_authenticated/macro/growth'
    | '/_authenticated/security/$symbol'
    | '/_authenticated/security/'
    | '/api/public/history/verify-narratives'
    | '/api/public/ingest/altdata'
    | '/api/public/ingest/commodities'
    | '/api/public/ingest/fred'
    | '/api/public/ingest/fundamentals'
    | '/api/public/ingest/macro-native'
    | '/api/public/ingest/stooq'
    | '/api/public/ingest/us-growth-fred'
    | '/api/public/providers/ping'
    | '/api/public/scores/run'
    | '/api/public/verify/run'
    | '/api/public/radars/undervaluation/refresh'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
  ApiPublicHistoryVerifyNarrativesRoute: typeof ApiPublicHistoryVerifyNarrativesRoute
  ApiPublicIngestAltdataRoute: typeof ApiPublicIngestAltdataRoute
  ApiPublicIngestCommoditiesRoute: typeof ApiPublicIngestCommoditiesRoute
  ApiPublicIngestFredRoute: typeof ApiPublicIngestFredRoute
  ApiPublicIngestFundamentalsRoute: typeof ApiPublicIngestFundamentalsRoute
  ApiPublicIngestMacroNativeRoute: typeof ApiPublicIngestMacroNativeRoute
  ApiPublicIngestStooqRoute: typeof ApiPublicIngestStooqRoute
  ApiPublicIngestUsGrowthFredRoute: typeof ApiPublicIngestUsGrowthFredRoute
  ApiPublicProvidersPingRoute: typeof ApiPublicProvidersPingRoute
  ApiPublicScoresRunRoute: typeof ApiPublicScoresRunRoute
  ApiPublicVerifyRunRoute: typeof ApiPublicVerifyRunRoute
  ApiPublicRadarsUndervaluationRefreshRoute: typeof ApiPublicRadarsUndervaluationRefreshRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/': {
      id: '/_authenticated/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/undervaluation': {
      id: '/_authenticated/undervaluation'
      path: '/undervaluation'
      fullPath: '/undervaluation'
      preLoaderRoute: typeof AuthenticatedUndervaluationRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/screeners': {
      id: '/_authenticated/screeners'
      path: '/screeners'
      fullPath: '/screeners'
      preLoaderRoute: typeof AuthenticatedScreenersRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/radar': {
      id: '/_authenticated/radar'
      path: '/radar'
      fullPath: '/radar'
      preLoaderRoute: typeof AuthenticatedRadarRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/overvaluation': {
      id: '/_authenticated/overvaluation'
      path: '/overvaluation'
      fullPath: '/overvaluation'
      preLoaderRoute: typeof AuthenticatedOvervaluationRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/macro': {
      id: '/_authenticated/macro'
      path: '/macro'
      fullPath: '/macro'
      preLoaderRoute: typeof AuthenticatedMacroRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/history': {
      id: '/_authenticated/history'
      path: '/history'
      fullPath: '/history'
      preLoaderRoute: typeof AuthenticatedHistoryRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/data-health': {
      id: '/_authenticated/data-health'
      path: '/data-health'
      fullPath: '/data-health'
      preLoaderRoute: typeof AuthenticatedDataHealthRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/alt-data': {
      id: '/_authenticated/alt-data'
      path: '/alt-data'
      fullPath: '/alt-data'
      preLoaderRoute: typeof AuthenticatedAltDataRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/alerts': {
      id: '/_authenticated/alerts'
      path: '/alerts'
      fullPath: '/alerts'
      preLoaderRoute: typeof AuthenticatedAlertsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/security/': {
      id: '/_authenticated/security/'
      path: '/security'
      fullPath: '/security/'
      preLoaderRoute: typeof AuthenticatedSecurityIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/security/$symbol': {
      id: '/_authenticated/security/$symbol'
      path: '/security/$symbol'
      fullPath: '/security/$symbol'
      preLoaderRoute: typeof AuthenticatedSecuritySymbolRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/macro/growth': {
      id: '/_authenticated/macro/growth'
      path: '/growth'
      fullPath: '/macro/growth'
      preLoaderRoute: typeof AuthenticatedMacroGrowthRouteImport
      parentRoute: typeof AuthenticatedMacroRoute
    }
    '/_authenticated/macro/$': {
      id: '/_authenticated/macro/$'
      path: '/$'
      fullPath: '/macro/$'
      preLoaderRoute: typeof AuthenticatedMacroSplatRouteImport
      parentRoute: typeof AuthenticatedMacroRoute
    }
    '/_authenticated/history/$eventId': {
      id: '/_authenticated/history/$eventId'
      path: '/$eventId'
      fullPath: '/history/$eventId'
      preLoaderRoute: typeof AuthenticatedHistoryEventIdRouteImport
      parentRoute: typeof AuthenticatedHistoryRoute
    }
    '/_authenticated/history/$': {
      id: '/_authenticated/history/$'
      path: '/$'
      fullPath: '/history/$'
      preLoaderRoute: typeof AuthenticatedHistorySplatRouteImport
      parentRoute: typeof AuthenticatedHistoryRoute
    }
    '/_authenticated/alt-data/$': {
      id: '/_authenticated/alt-data/$'
      path: '/$'
      fullPath: '/alt-data/$'
      preLoaderRoute: typeof AuthenticatedAltDataSplatRouteImport
      parentRoute: typeof AuthenticatedAltDataRoute
    }
    '/api/public/verify/run': {
      id: '/api/public/verify/run'
      path: '/api/public/verify/run'
      fullPath: '/api/public/verify/run'
      preLoaderRoute: typeof ApiPublicVerifyRunRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/scores/run': {
      id: '/api/public/scores/run'
      path: '/api/public/scores/run'
      fullPath: '/api/public/scores/run'
      preLoaderRoute: typeof ApiPublicScoresRunRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/providers/ping': {
      id: '/api/public/providers/ping'
      path: '/api/public/providers/ping'
      fullPath: '/api/public/providers/ping'
      preLoaderRoute: typeof ApiPublicProvidersPingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/ingest/us-growth-fred': {
      id: '/api/public/ingest/us-growth-fred'
      path: '/api/public/ingest/us-growth-fred'
      fullPath: '/api/public/ingest/us-growth-fred'
      preLoaderRoute: typeof ApiPublicIngestUsGrowthFredRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/ingest/stooq': {
      id: '/api/public/ingest/stooq'
      path: '/api/public/ingest/stooq'
      fullPath: '/api/public/ingest/stooq'
      preLoaderRoute: typeof ApiPublicIngestStooqRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/ingest/macro-native': {
      id: '/api/public/ingest/macro-native'
      path: '/api/public/ingest/macro-native'
      fullPath: '/api/public/ingest/macro-native'
      preLoaderRoute: typeof ApiPublicIngestMacroNativeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/ingest/fundamentals': {
      id: '/api/public/ingest/fundamentals'
      path: '/api/public/ingest/fundamentals'
      fullPath: '/api/public/ingest/fundamentals'
      preLoaderRoute: typeof ApiPublicIngestFundamentalsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/ingest/fred': {
      id: '/api/public/ingest/fred'
      path: '/api/public/ingest/fred'
      fullPath: '/api/public/ingest/fred'
      preLoaderRoute: typeof ApiPublicIngestFredRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/ingest/commodities': {
      id: '/api/public/ingest/commodities'
      path: '/api/public/ingest/commodities'
      fullPath: '/api/public/ingest/commodities'
      preLoaderRoute: typeof ApiPublicIngestCommoditiesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/ingest/altdata': {
      id: '/api/public/ingest/altdata'
      path: '/api/public/ingest/altdata'
      fullPath: '/api/public/ingest/altdata'
      preLoaderRoute: typeof ApiPublicIngestAltdataRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/history/verify-narratives': {
      id: '/api/public/history/verify-narratives'
      path: '/api/public/history/verify-narratives'
      fullPath: '/api/public/history/verify-narratives'
      preLoaderRoute: typeof ApiPublicHistoryVerifyNarrativesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/radars/undervaluation/refresh': {
      id: '/api/public/radars/undervaluation/refresh'
      path: '/api/public/radars/undervaluation/refresh'
      fullPath: '/api/public/radars/undervaluation/refresh'
      preLoaderRoute: typeof ApiPublicRadarsUndervaluationRefreshRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AuthenticatedAltDataRouteChildren {
  AuthenticatedAltDataSplatRoute: typeof AuthenticatedAltDataSplatRoute
}

const AuthenticatedAltDataRouteChildren: AuthenticatedAltDataRouteChildren = {
  AuthenticatedAltDataSplatRoute: AuthenticatedAltDataSplatRoute,
}

const AuthenticatedAltDataRouteWithChildren =
  AuthenticatedAltDataRoute._addFileChildren(AuthenticatedAltDataRouteChildren)

interface AuthenticatedHistoryRouteChildren {
  AuthenticatedHistorySplatRoute: typeof AuthenticatedHistorySplatRoute
  AuthenticatedHistoryEventIdRoute: typeof AuthenticatedHistoryEventIdRoute
}

const AuthenticatedHistoryRouteChildren: AuthenticatedHistoryRouteChildren = {
  AuthenticatedHistorySplatRoute: AuthenticatedHistorySplatRoute,
  AuthenticatedHistoryEventIdRoute: AuthenticatedHistoryEventIdRoute,
}

const AuthenticatedHistoryRouteWithChildren =
  AuthenticatedHistoryRoute._addFileChildren(AuthenticatedHistoryRouteChildren)

interface AuthenticatedMacroRouteChildren {
  AuthenticatedMacroSplatRoute: typeof AuthenticatedMacroSplatRoute
  AuthenticatedMacroGrowthRoute: typeof AuthenticatedMacroGrowthRoute
}

const AuthenticatedMacroRouteChildren: AuthenticatedMacroRouteChildren = {
  AuthenticatedMacroSplatRoute: AuthenticatedMacroSplatRoute,
  AuthenticatedMacroGrowthRoute: AuthenticatedMacroGrowthRoute,
}

const AuthenticatedMacroRouteWithChildren =
  AuthenticatedMacroRoute._addFileChildren(AuthenticatedMacroRouteChildren)

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAlertsRoute: typeof AuthenticatedAlertsRoute
  AuthenticatedAltDataRoute: typeof AuthenticatedAltDataRouteWithChildren
  AuthenticatedDataHealthRoute: typeof AuthenticatedDataHealthRoute
  AuthenticatedHistoryRoute: typeof AuthenticatedHistoryRouteWithChildren
  AuthenticatedMacroRoute: typeof AuthenticatedMacroRouteWithChildren
  AuthenticatedOvervaluationRoute: typeof AuthenticatedOvervaluationRoute
  AuthenticatedRadarRoute: typeof AuthenticatedRadarRoute
  AuthenticatedScreenersRoute: typeof AuthenticatedScreenersRoute
  AuthenticatedUndervaluationRoute: typeof AuthenticatedUndervaluationRoute
  AuthenticatedIndexRoute: typeof AuthenticatedIndexRoute
  AuthenticatedSecuritySymbolRoute: typeof AuthenticatedSecuritySymbolRoute
  AuthenticatedSecurityIndexRoute: typeof AuthenticatedSecurityIndexRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAlertsRoute: AuthenticatedAlertsRoute,
  AuthenticatedAltDataRoute: AuthenticatedAltDataRouteWithChildren,
  AuthenticatedDataHealthRoute: AuthenticatedDataHealthRoute,
  AuthenticatedHistoryRoute: AuthenticatedHistoryRouteWithChildren,
  AuthenticatedMacroRoute: AuthenticatedMacroRouteWithChildren,
  AuthenticatedOvervaluationRoute: AuthenticatedOvervaluationRoute,
  AuthenticatedRadarRoute: AuthenticatedRadarRoute,
  AuthenticatedScreenersRoute: AuthenticatedScreenersRoute,
  AuthenticatedUndervaluationRoute: AuthenticatedUndervaluationRoute,
  AuthenticatedIndexRoute: AuthenticatedIndexRoute,
  AuthenticatedSecuritySymbolRoute: AuthenticatedSecuritySymbolRoute,
  AuthenticatedSecurityIndexRoute: AuthenticatedSecurityIndexRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
  ApiPublicHistoryVerifyNarrativesRoute: ApiPublicHistoryVerifyNarrativesRoute,
  ApiPublicIngestAltdataRoute: ApiPublicIngestAltdataRoute,
  ApiPublicIngestCommoditiesRoute: ApiPublicIngestCommoditiesRoute,
  ApiPublicIngestFredRoute: ApiPublicIngestFredRoute,
  ApiPublicIngestFundamentalsRoute: ApiPublicIngestFundamentalsRoute,
  ApiPublicIngestMacroNativeRoute: ApiPublicIngestMacroNativeRoute,
  ApiPublicIngestStooqRoute: ApiPublicIngestStooqRoute,
  ApiPublicIngestUsGrowthFredRoute: ApiPublicIngestUsGrowthFredRoute,
  ApiPublicProvidersPingRoute: ApiPublicProvidersPingRoute,
  ApiPublicScoresRunRoute: ApiPublicScoresRunRoute,
  ApiPublicVerifyRunRoute: ApiPublicVerifyRunRoute,
  ApiPublicRadarsUndervaluationRefreshRoute:
    ApiPublicRadarsUndervaluationRefreshRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
