/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ScreenersRouteImport } from './routes/screeners'
import { Route as RadarRouteImport } from './routes/radar'
import { Route as MacroRouteImport } from './routes/macro'
import { Route as HistoryRouteImport } from './routes/history'
import { Route as DataHealthRouteImport } from './routes/data-health'
import { Route as AltDataRouteImport } from './routes/alt-data'
import { Route as AlertsRouteImport } from './routes/alerts'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ApiPublicVerifyRunRouteImport } from './routes/api/public/verify/run'
import { Route as ApiPublicIngestFredRouteImport } from './routes/api/public/ingest/fred'

const ScreenersRoute = ScreenersRouteImport.update({
  id: '/screeners',
  path: '/screeners',
  getParentRoute: () => rootRouteImport,
} as any)
const RadarRoute = RadarRouteImport.update({
  id: '/radar',
  path: '/radar',
  getParentRoute: () => rootRouteImport,
} as any)
const MacroRoute = MacroRouteImport.update({
  id: '/macro',
  path: '/macro',
  getParentRoute: () => rootRouteImport,
} as any)
const HistoryRoute = HistoryRouteImport.update({
  id: '/history',
  path: '/history',
  getParentRoute: () => rootRouteImport,
} as any)
const DataHealthRoute = DataHealthRouteImport.update({
  id: '/data-health',
  path: '/data-health',
  getParentRoute: () => rootRouteImport,
} as any)
const AltDataRoute = AltDataRouteImport.update({
  id: '/alt-data',
  path: '/alt-data',
  getParentRoute: () => rootRouteImport,
} as any)
const AlertsRoute = AlertsRouteImport.update({
  id: '/alerts',
  path: '/alerts',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicVerifyRunRoute = ApiPublicVerifyRunRouteImport.update({
  id: '/api/public/verify/run',
  path: '/api/public/verify/run',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicIngestFredRoute = ApiPublicIngestFredRouteImport.update({
  id: '/api/public/ingest/fred',
  path: '/api/public/ingest/fred',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/alerts': typeof AlertsRoute
  '/alt-data': typeof AltDataRoute
  '/data-health': typeof DataHealthRoute
  '/history': typeof HistoryRoute
  '/macro': typeof MacroRoute
  '/radar': typeof RadarRoute
  '/screeners': typeof ScreenersRoute
  '/api/public/ingest/fred': typeof ApiPublicIngestFredRoute
  '/api/public/verify/run': typeof ApiPublicVerifyRunRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/alerts': typeof AlertsRoute
  '/alt-data': typeof AltDataRoute
  '/data-health': typeof DataHealthRoute
  '/history': typeof HistoryRoute
  '/macro': typeof MacroRoute
  '/radar': typeof RadarRoute
  '/screeners': typeof ScreenersRoute
  '/api/public/ingest/fred': typeof ApiPublicIngestFredRoute
  '/api/public/verify/run': typeof ApiPublicVerifyRunRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/alerts': typeof AlertsRoute
  '/alt-data': typeof AltDataRoute
  '/data-health': typeof DataHealthRoute
  '/history': typeof HistoryRoute
  '/macro': typeof MacroRoute
  '/radar': typeof RadarRoute
  '/screeners': typeof ScreenersRoute
  '/api/public/ingest/fred': typeof ApiPublicIngestFredRoute
  '/api/public/verify/run': typeof ApiPublicVerifyRunRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/alerts'
    | '/alt-data'
    | '/data-health'
    | '/history'
    | '/macro'
    | '/radar'
    | '/screeners'
    | '/api/public/ingest/fred'
    | '/api/public/verify/run'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/alerts'
    | '/alt-data'
    | '/data-health'
    | '/history'
    | '/macro'
    | '/radar'
    | '/screeners'
    | '/api/public/ingest/fred'
    | '/api/public/verify/run'
  id:
    | '__root__'
    | '/'
    | '/alerts'
    | '/alt-data'
    | '/data-health'
    | '/history'
    | '/macro'
    | '/radar'
    | '/screeners'
    | '/api/public/ingest/fred'
    | '/api/public/verify/run'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AlertsRoute: typeof AlertsRoute
  AltDataRoute: typeof AltDataRoute
  DataHealthRoute: typeof DataHealthRoute
  HistoryRoute: typeof HistoryRoute
  MacroRoute: typeof MacroRoute
  RadarRoute: typeof RadarRoute
  ScreenersRoute: typeof ScreenersRoute
  ApiPublicIngestFredRoute: typeof ApiPublicIngestFredRoute
  ApiPublicVerifyRunRoute: typeof ApiPublicVerifyRunRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/screeners': {
      id: '/screeners'
      path: '/screeners'
      fullPath: '/screeners'
      preLoaderRoute: typeof ScreenersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/radar': {
      id: '/radar'
      path: '/radar'
      fullPath: '/radar'
      preLoaderRoute: typeof RadarRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/macro': {
      id: '/macro'
      path: '/macro'
      fullPath: '/macro'
      preLoaderRoute: typeof MacroRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/history': {
      id: '/history'
      path: '/history'
      fullPath: '/history'
      preLoaderRoute: typeof HistoryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/data-health': {
      id: '/data-health'
      path: '/data-health'
      fullPath: '/data-health'
      preLoaderRoute: typeof DataHealthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/alt-data': {
      id: '/alt-data'
      path: '/alt-data'
      fullPath: '/alt-data'
      preLoaderRoute: typeof AltDataRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/alerts': {
      id: '/alerts'
      path: '/alerts'
      fullPath: '/alerts'
      preLoaderRoute: typeof AlertsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/verify/run': {
      id: '/api/public/verify/run'
      path: '/api/public/verify/run'
      fullPath: '/api/public/verify/run'
      preLoaderRoute: typeof ApiPublicVerifyRunRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/ingest/fred': {
      id: '/api/public/ingest/fred'
      path: '/api/public/ingest/fred'
      fullPath: '/api/public/ingest/fred'
      preLoaderRoute: typeof ApiPublicIngestFredRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AlertsRoute: AlertsRoute,
  AltDataRoute: AltDataRoute,
  DataHealthRoute: DataHealthRoute,
  HistoryRoute: HistoryRoute,
  MacroRoute: MacroRoute,
  RadarRoute: RadarRoute,
  ScreenersRoute: ScreenersRoute,
  ApiPublicIngestFredRoute: ApiPublicIngestFredRoute,
  ApiPublicVerifyRunRoute: ApiPublicVerifyRunRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
