-- Persist point-in-time swing signals and their subsequent outcomes. The signal
-- snapshot is immutable evidence: later model changes must not rewrite the
-- conditions that existed when the setup was first surfaced.

CREATE EXTENSION IF NOT EXISTS pg_cron;
CREATE EXTENSION IF NOT EXISTS pg_net;

CREATE TABLE IF NOT EXISTS public.swing_trade_setups (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  asset_id uuid NOT NULL REFERENCES public.assets(id) ON DELETE CASCADE,
  model_version text NOT NULL,
  setup_type text NOT NULL,
  setup_label text NOT NULL,
  signal_state text NOT NULL,
  setup_score numeric NOT NULL,
  evidence_coverage numeric NOT NULL,
  high_conviction boolean NOT NULL DEFAULT false,
  signal_at timestamptz NOT NULL DEFAULT now(),
  price_as_of date NOT NULL,
  signal_price numeric NOT NULL,
  entry_low numeric NOT NULL,
  entry_high numeric NOT NULL,
  entry_mid numeric NOT NULL,
  invalidation numeric NOT NULL,
  target numeric NOT NULL,
  reward_risk numeric NOT NULL,
  atr14 numeric,
  horizon_sessions integer NOT NULL DEFAULT 40,
  components jsonb NOT NULL DEFAULT '{}'::jsonb,
  metrics jsonb NOT NULL DEFAULT '{}'::jsonb,
  reasons jsonb NOT NULL DEFAULT '[]'::jsonb,
  risks jsonb NOT NULL DEFAULT '[]'::jsonb,
  outcome_status text NOT NULL DEFAULT 'active',
  target_behaviour text NOT NULL DEFAULT 'pending',
  sessions_observed integer NOT NULL DEFAULT 0,
  target_hit_at timestamptz,
  stop_hit_at timestamptz,
  resolved_at timestamptz,
  max_price numeric,
  min_price numeric,
  max_favourable_pct numeric,
  max_adverse_pct numeric,
  target_overshoot_pct numeric,
  target_shortfall_pct numeric,
  latest_return_pct numeric,
  calibration_eligible boolean NOT NULL DEFAULT false,
  last_evaluated_at timestamptz,
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now(),
  CONSTRAINT swing_trade_geometry_valid CHECK (
    entry_low > 0 AND entry_high >= entry_low AND entry_mid > 0 AND
    invalidation > 0 AND invalidation < entry_mid AND target > entry_mid
  ),
  CONSTRAINT swing_trade_horizon_valid CHECK (horizon_sessions BETWEEN 1 AND 120)
);

CREATE UNIQUE INDEX IF NOT EXISTS swing_trade_setup_signal_key
  ON public.swing_trade_setups(asset_id, setup_type, price_as_of, model_version);

CREATE INDEX IF NOT EXISTS swing_trade_setups_active_idx
  ON public.swing_trade_setups(outcome_status, high_conviction DESC, setup_score DESC, signal_at DESC);

CREATE INDEX IF NOT EXISTS swing_trade_setups_asset_idx
  ON public.swing_trade_setups(asset_id, signal_at DESC);

CREATE TABLE IF NOT EXISTS public.swing_trade_price_snapshots (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  setup_id uuid NOT NULL REFERENCES public.swing_trade_setups(id) ON DELETE CASCADE,
  asset_id uuid NOT NULL REFERENCES public.assets(id) ON DELETE CASCADE,
  observed_at timestamptz NOT NULL DEFAULT now(),
  price numeric NOT NULL,
  day_high numeric,
  day_low numeric,
  volume numeric,
  provider text NOT NULL,
  source_kind text NOT NULL DEFAULT 'intraday_quote',
  created_at timestamptz NOT NULL DEFAULT now(),
  CONSTRAINT swing_trade_snapshot_price_valid CHECK (price > 0),
  CONSTRAINT swing_trade_snapshot_range_valid CHECK (
    (day_high IS NULL OR day_high > 0) AND
    (day_low IS NULL OR day_low > 0) AND
    (day_high IS NULL OR day_low IS NULL OR day_high >= day_low)
  )
);

CREATE INDEX IF NOT EXISTS swing_trade_price_snapshots_setup_idx
  ON public.swing_trade_price_snapshots(setup_id, observed_at DESC);

CREATE INDEX IF NOT EXISTS swing_trade_price_snapshots_asset_idx
  ON public.swing_trade_price_snapshots(asset_id, observed_at DESC);

ALTER TABLE public.swing_trade_setups ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.swing_trade_price_snapshots ENABLE ROW LEVEL SECURITY;

-- Remove an older copy of the monitor if this migration is replayed.
DO $$
DECLARE
  existing_job RECORD;
BEGIN
  FOR existing_job IN
    SELECT jobid
    FROM cron.job
    WHERE jobname = 'swing-trade-intraday-monitor'
  LOOP
    PERFORM cron.unschedule(existing_job.jobid);
  END LOOP;
END $$;

-- Refresh the strongest active swing setups hourly through the overlapping UK,
-- EU and US trading window. The application-side monitor is quota-aware and
-- limits live quote requests to the highest-priority active setups, while daily
-- bars remain the authoritative source for final target/stop classification.
SELECT cron.schedule(
  'swing-trade-intraday-monitor',
  '10 7-20 * * 1-5',
  $cron$
  SELECT net.http_post(
    url := 'https://project--d87a6acb-6341-458d-8dd2-3a8d0894569f.lovable.app/api/public/ingest/stooq?swingMonitor=1',
    headers := jsonb_build_object(
      'Content-Type', 'application/json',
      'apikey', 'eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Iml0ZndvamlteHV4d214amNvbHp0Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3ODQ1NzEwMzIsImV4cCI6MjEwMDE0NzAzMn0.ysFIVxKkUIZEdma74PYlINR-ZfI9BU_J4beHMB0Xf80'
    ),
    body := '{"source":"cron","job":"swing-trade-intraday-monitor","cadence":"hourly"}'::jsonb,
    timeout_milliseconds := 300000
  ) AS request_id;
  $cron$
);
