CREATE EXTENSION IF NOT EXISTS pg_cron;
CREATE EXTENSION IF NOT EXISTS pg_net;

CREATE TABLE IF NOT EXISTS public.swing_trade_setups (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  asset_id uuid NOT NULL REFERENCES public.assets(id) ON DELETE CASCADE,
  model_version text NOT NULL,
  setup_type text NOT NULL,
  setup_label text NOT NULL,
  signal_state text NOT NULL,
  setup_score numeric NOT NULL,
  evidence_coverage numeric NOT NULL,
  high_conviction boolean NOT NULL DEFAULT false,
  signal_at timestamptz NOT NULL DEFAULT now(),
  price_as_of date NOT NULL,
  signal_price numeric NOT NULL,
  entry_low numeric NOT NULL,
  entry_high numeric NOT NULL,
  entry_mid numeric NOT NULL,
  invalidation numeric NOT NULL,
  target numeric NOT NULL,
  reward_risk numeric NOT NULL,
  atr14 numeric,
  horizon_sessions integer NOT NULL DEFAULT 40,
  components jsonb NOT NULL DEFAULT '{}'::jsonb,
  metrics jsonb NOT NULL DEFAULT '{}'::jsonb,
  reasons jsonb NOT NULL DEFAULT '[]'::jsonb,
  risks jsonb NOT NULL DEFAULT '[]'::jsonb,
  outcome_status text NOT NULL DEFAULT 'active',
  target_behaviour text NOT NULL DEFAULT 'pending',
  sessions_observed integer NOT NULL DEFAULT 0,
  target_hit_at timestamptz,
  stop_hit_at timestamptz,
  resolved_at timestamptz,
  max_price numeric,
  min_price numeric,
  max_favourable_pct numeric,
  max_adverse_pct numeric,
  target_overshoot_pct numeric,
  target_shortfall_pct numeric,
  latest_return_pct numeric,
  calibration_eligible boolean NOT NULL DEFAULT false,
  last_evaluated_at timestamptz,
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now(),
  CONSTRAINT swing_trade_geometry_valid CHECK (
    entry_low > 0 AND entry_high >= entry_low AND entry_mid > 0 AND
    invalidation > 0 AND invalidation < entry_mid AND target > entry_mid
  ),
  CONSTRAINT swing_trade_horizon_valid CHECK (horizon_sessions BETWEEN 1 AND 120)
);

CREATE UNIQUE INDEX IF NOT EXISTS swing_trade_setup_signal_key
  ON public.swing_trade_setups(asset_id, setup_type, price_as_of, model_version);
CREATE INDEX IF NOT EXISTS swing_trade_setups_active_idx
  ON public.swing_trade_setups(outcome_status, high_conviction DESC, setup_score DESC, signal_at DESC);
CREATE INDEX IF NOT EXISTS swing_trade_setups_asset_idx
  ON public.swing_trade_setups(asset_id, signal_at DESC);

CREATE TABLE IF NOT EXISTS public.swing_trade_price_snapshots (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  setup_id uuid NOT NULL REFERENCES public.swing_trade_setups(id) ON DELETE CASCADE,
  asset_id uuid NOT NULL REFERENCES public.assets(id) ON DELETE CASCADE,
  observed_at timestamptz NOT NULL DEFAULT now(),
  price numeric NOT NULL,
  day_high numeric,
  day_low numeric,
  volume numeric,
  provider text NOT NULL,
  source_kind text NOT NULL DEFAULT 'intraday_quote',
  created_at timestamptz NOT NULL DEFAULT now(),
  CONSTRAINT swing_trade_snapshot_price_valid CHECK (price > 0),
  CONSTRAINT swing_trade_snapshot_range_valid CHECK (
    (day_high IS NULL OR day_high > 0) AND
    (day_low IS NULL OR day_low > 0) AND
    (day_high IS NULL OR day_low IS NULL OR day_high >= day_low)
  )
);

CREATE INDEX IF NOT EXISTS swing_trade_price_snapshots_setup_idx
  ON public.swing_trade_price_snapshots(setup_id, observed_at DESC);
CREATE INDEX IF NOT EXISTS swing_trade_price_snapshots_asset_idx
  ON public.swing_trade_price_snapshots(asset_id, observed_at DESC);

CREATE TABLE IF NOT EXISTS public.equity_eod_backfill_queue (
  market_date date PRIMARY KEY,
  status text NOT NULL DEFAULT 'pending',
  attempts integer NOT NULL DEFAULT 0,
  last_error text,
  completed_at timestamptz,
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now(),
  CONSTRAINT equity_eod_backfill_status_valid CHECK (
    status IN ('pending', 'running', 'complete', 'no_data', 'failed')
  ),
  CONSTRAINT equity_eod_backfill_attempts_valid CHECK (attempts >= 0)
);

CREATE INDEX IF NOT EXISTS equity_eod_backfill_pending_idx
  ON public.equity_eod_backfill_queue(status, market_date DESC);

CREATE TABLE IF NOT EXISTS public.equity_technical_screen (
  asset_id uuid PRIMARY KEY REFERENCES public.assets(id) ON DELETE CASCADE,
  as_of date NOT NULL,
  bars integer NOT NULL,
  current_price numeric,
  return_5d_pct numeric,
  return_20d_pct numeric,
  ma20 numeric,
  ma50 numeric,
  high_90 numeric,
  low_90 numeric,
  latest_volume numeric,
  avg_volume_20 numeric,
  relative_volume numeric,
  updated_at timestamptz NOT NULL DEFAULT now(),
  CONSTRAINT equity_technical_screen_bars_valid CHECK (bars >= 0)
);

CREATE INDEX IF NOT EXISTS equity_technical_screen_asof_idx
  ON public.equity_technical_screen(as_of DESC, bars DESC);
CREATE INDEX IF NOT EXISTS equity_technical_screen_return20_idx
  ON public.equity_technical_screen(return_20d_pct DESC NULLS LAST);
CREATE INDEX IF NOT EXISTS equity_technical_screen_relvol_idx
  ON public.equity_technical_screen(relative_volume DESC NULLS LAST);

CREATE TABLE IF NOT EXISTS public.swing_monitor_runs (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  source text NOT NULL DEFAULT 'scheduled',
  status text NOT NULL DEFAULT 'running',
  started_at timestamptz NOT NULL DEFAULT now(),
  finished_at timestamptz,
  workspace_as_of date,
  screened integer NOT NULL DEFAULT 0,
  deep_scanned integer NOT NULL DEFAULT 0,
  surfaced integer NOT NULL DEFAULT 0,
  captured integer NOT NULL DEFAULT 0,
  evaluated integer NOT NULL DEFAULT 0,
  quotes_updated integer NOT NULL DEFAULT 0,
  failures jsonb NOT NULL DEFAULT '[]'::jsonb,
  providers jsonb NOT NULL DEFAULT '{}'::jsonb,
  error text,
  CONSTRAINT swing_monitor_run_status_valid CHECK (status IN ('running', 'success', 'failed'))
);

CREATE INDEX IF NOT EXISTS swing_monitor_runs_started_idx
  ON public.swing_monitor_runs(started_at DESC);
CREATE INDEX IF NOT EXISTS swing_monitor_runs_status_idx
  ON public.swing_monitor_runs(status, started_at DESC);

GRANT ALL ON public.swing_trade_setups TO service_role;
GRANT ALL ON public.swing_trade_price_snapshots TO service_role;
GRANT ALL ON public.swing_monitor_runs TO service_role;
GRANT ALL ON public.equity_technical_screen TO service_role;
GRANT ALL ON public.equity_eod_backfill_queue TO service_role;
GRANT USAGE, SELECT ON SEQUENCE public.swing_trade_price_snapshots_id_seq TO service_role;

ALTER TABLE public.swing_trade_setups ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.swing_trade_price_snapshots ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.swing_monitor_runs ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.equity_technical_screen ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.equity_eod_backfill_queue ENABLE ROW LEVEL SECURITY;

CREATE OR REPLACE FUNCTION public.refresh_equity_technical_screen()
RETURNS integer
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $$
DECLARE
  affected integer := 0;
BEGIN
  WITH ranked AS (
    SELECT
      p.asset_id,
      p.trade_date,
      p.open,
      p.high,
      p.low,
      p.close,
      p.volume,
      row_number() OVER (
        PARTITION BY p.asset_id
        ORDER BY p.trade_date DESC
      ) AS rn
    FROM public.prices_daily p
    JOIN public.assets a ON a.id = p.asset_id
    WHERE a.active = true
      AND a.asset_class = 'equity'
      AND p.close IS NOT NULL
      AND p.trade_date >= current_date - interval '430 days'
  ), aggregated AS (
    SELECT
      asset_id,
      max(trade_date) FILTER (WHERE rn = 1) AS as_of,
      count(*)::integer AS bars,
      max(close) FILTER (WHERE rn = 1) AS current_price,
      max(close) FILTER (WHERE rn = 6) AS close_5d,
      max(close) FILTER (WHERE rn = 21) AS close_20d,
      avg(close) FILTER (WHERE rn <= 20) AS ma20,
      avg(close) FILTER (WHERE rn <= 50) AS ma50,
      max(high) FILTER (WHERE rn <= 90) AS high_90,
      min(low) FILTER (WHERE rn <= 90) AS low_90,
      max(volume) FILTER (WHERE rn = 1) AS latest_volume,
      avg(volume) FILTER (WHERE rn BETWEEN 2 AND 21 AND volume IS NOT NULL) AS avg_volume_20
    FROM ranked
    GROUP BY asset_id
  )
  INSERT INTO public.equity_technical_screen (
    asset_id, as_of, bars, current_price, return_5d_pct, return_20d_pct,
    ma20, ma50, high_90, low_90, latest_volume, avg_volume_20, relative_volume, updated_at
  )
  SELECT
    asset_id,
    as_of,
    bars,
    current_price,
    CASE WHEN current_price > 0 AND close_5d > 0 THEN (current_price / close_5d - 1) * 100 ELSE NULL END,
    CASE WHEN current_price > 0 AND close_20d > 0 THEN (current_price / close_20d - 1) * 100 ELSE NULL END,
    ma20,
    ma50,
    high_90,
    low_90,
    latest_volume,
    avg_volume_20,
    CASE WHEN latest_volume IS NOT NULL AND avg_volume_20 > 0 THEN latest_volume / avg_volume_20 ELSE NULL END,
    now()
  FROM aggregated
  WHERE as_of IS NOT NULL
  ON CONFLICT (asset_id) DO UPDATE SET
    as_of = EXCLUDED.as_of,
    bars = EXCLUDED.bars,
    current_price = EXCLUDED.current_price,
    return_5d_pct = EXCLUDED.return_5d_pct,
    return_20d_pct = EXCLUDED.return_20d_pct,
    ma20 = EXCLUDED.ma20,
    ma50 = EXCLUDED.ma50,
    high_90 = EXCLUDED.high_90,
    low_90 = EXCLUDED.low_90,
    latest_volume = EXCLUDED.latest_volume,
    avg_volume_20 = EXCLUDED.avg_volume_20,
    relative_volume = EXCLUDED.relative_volume,
    updated_at = now();

  GET DIAGNOSTICS affected = ROW_COUNT;
  RETURN affected;
END;
$$;

REVOKE ALL ON FUNCTION public.refresh_equity_technical_screen() FROM PUBLIC;
GRANT EXECUTE ON FUNCTION public.refresh_equity_technical_screen() TO service_role;

INSERT INTO public.equity_eod_backfill_queue (market_date)
SELECT d::date
FROM generate_series(
  current_date - interval '190 days',
  current_date - interval '2 days',
  interval '1 day'
) AS d
WHERE extract(isodow FROM d) BETWEEN 1 AND 5
ON CONFLICT (market_date) DO NOTHING;

DO $$
DECLARE
  existing_job RECORD;
BEGIN
  FOR existing_job IN
    SELECT jobid FROM cron.job
    WHERE jobname IN (
      'equity-universe-refresh',
      'equity-universe-monday-recovery',
      'swing-trade-intraday-monitor',
      'swing-monitor',
      'swing-trade-monitor',
      'equity-price-refresh',
      'equity-eod-bulk-refresh',
      'equity-eod-bulk-backfill'
    )
  LOOP
    PERFORM cron.unschedule(existing_job.jobid);
  END LOOP;
END $$;

SELECT cron.schedule(
  'equity-universe-refresh',
  '10 4 * * 0',
  $cron$
  SELECT net.http_post(
    url := 'https://project--d87a6acb-6341-458d-8dd2-3a8d0894569f.lovable.app/api/public/ingest/stooq?syncUniverse=1&limit=3000&markets=US,UK,EU',
    headers := jsonb_build_object(
      'Content-Type', 'application/json',
      'apikey', 'eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Iml0ZndvamlteHV4d214amNvbHp0Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3ODQ1NzEwMzIsImV4cCI6MjEwMDE0NzAzMn0.ysFIVxKkUIZEdma74PYlINR-ZfI9BU_J4beHMB0Xf80'
    ),
    body := '{"source":"cron","job":"equity-universe-refresh","target":3000}'::jsonb,
    timeout_milliseconds := 300000
  ) AS request_id;
  $cron$
);

SELECT cron.schedule(
  'equity-universe-monday-recovery',
  '40 4 * * 1',
  $cron$
  SELECT net.http_post(
    url := 'https://project--d87a6acb-6341-458d-8dd2-3a8d0894569f.lovable.app/api/public/ingest/stooq?limit=250',
    headers := jsonb_build_object(
      'Content-Type', 'application/json',
      'apikey', 'eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Iml0ZndvamlteHV4d214amNvbHp0Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3ODQ1NzEwMzIsImV4cCI6MjEwMDE0NzAzMn0.ysFIVxKkUIZEdma74PYlINR-ZfI9BU_J4beHMB0Xf80'
    ),
    body := '{"source":"cron","job":"equity-universe-monday-recovery"}'::jsonb,
    timeout_milliseconds := 300000
  ) AS request_id;
  $cron$
);

SELECT cron.schedule(
  'equity-eod-bulk-refresh',
  '30 4 * * 2-6',
  $cron$
  SELECT net.http_post(
    url := 'https://project--d87a6acb-6341-458d-8dd2-3a8d0894569f.lovable.app/api/public/ingest/stooq?bulkEod=1',
    headers := jsonb_build_object(
      'Content-Type', 'application/json',
      'apikey', 'eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Iml0ZndvamlteHV4d214amNvbHp0Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3ODQ1NzEwMzIsImV4cCI6MjEwMDE0NzAzMn0.ysFIVxKkUIZEdma74PYlINR-ZfI9BU_J4beHMB0Xf80'
    ),
    body := '{"source":"cron","job":"equity-eod-bulk-refresh"}'::jsonb,
    timeout_milliseconds := 300000
  ) AS request_id;
  $cron$
);

SELECT cron.schedule(
  'equity-eod-bulk-backfill',
  '7,27,47 * * * *',
  $cron$
  SELECT net.http_post(
    url := 'https://project--d87a6acb-6341-458d-8dd2-3a8d0894569f.lovable.app/api/public/ingest/stooq?bulkBackfill=1&limitDates=4',
    headers := jsonb_build_object(
      'Content-Type', 'application/json',
      'apikey', 'eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Iml0ZndvamlteHV4d214amNvbHp0Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3ODQ1NzEwMzIsImV4cCI6MjEwMDE0NzAzMn0.ysFIVxKkUIZEdma74PYlINR-ZfI9BU_J4beHMB0Xf80'
    ),
    body := '{"source":"cron","job":"equity-eod-bulk-backfill","limitDates":4}'::jsonb,
    timeout_milliseconds := 300000
  ) AS request_id;
  $cron$
);

SELECT cron.schedule(
  'swing-monitor',
  '0,30 7-20 * * 1-5',
  $cron$
  SELECT net.http_post(
    url := 'https://project--d87a6acb-6341-458d-8dd2-3a8d0894569f.lovable.app/api/public/ingest/stooq?swingMonitor=1',
    headers := jsonb_build_object(
      'Content-Type', 'application/json',
      'apikey', 'eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Iml0ZndvamlteHV4d214amNvbHp0Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3ODQ1NzEwMzIsImV4cCI6MjEwMDE0NzAzMn0.ysFIVxKkUIZEdma74PYlINR-ZfI9BU_J4beHMB0Xf80'
    ),
    body := '{"source":"cron","job":"swing-monitor"}'::jsonb,
    timeout_milliseconds := 300000
  ) AS request_id;
  $cron$
);

SELECT public.refresh_equity_technical_screen();