/**
 * Ticker → Wikipedia article-title map for the alt-data attention signal.
 * Article titles use underscores (as URL path segments) and are case-sensitive.
 * Client-safe module (no server imports) so it can be referenced from panels.
 */
export const WIKIPEDIA_TITLES: Record<string, string> = {
  AAPL: "Apple_Inc.",
  ABBV: "AbbVie",
  ADBE: "Adobe_Inc.",
  AMD: "Advanced_Micro_Devices",
  AMT: "American_Tower",
  AMZN: "Amazon_(company)",
  AVGO: "Broadcom",
  BA: "Boeing",
  BAC: "Bank_of_America",
  BLK: "BlackRock",
  "BRK-B": "Berkshire_Hathaway",
  CAT: "Caterpillar_Inc.",
  COP: "ConocoPhillips",
  COST: "Costco",
  CRM: "Salesforce",
  CSCO: "Cisco",
  CVX: "Chevron_Corporation",
  DIS: "The_Walt_Disney_Company",
  DUK: "Duke_Energy",
  FCX: "Freeport-McMoRan",
  GE: "GE_Aerospace",
  GOOGL: "Alphabet_Inc.",
  GS: "Goldman_Sachs",
  HD: "The_Home_Depot",
  HON: "Honeywell",
  INTC: "Intel",
  JNJ: "Johnson_%26_Johnson",
  JPM: "JPMorgan_Chase",
  KO: "The_Coca-Cola_Company",
  LIN: "Linde_plc",
  LLY: "Eli_Lilly_and_Company",
  LOW: "Lowe%27s",
  MA: "Mastercard",
  MCD: "McDonald%27s",
  META: "Meta_Platforms",
  MRK: "Merck_%26_Co.",
  MS: "Morgan_Stanley",
  MSFT: "Microsoft",
  NEE: "NextEra_Energy",
  NFLX: "Netflix",
  NKE: "Nike,_Inc.",
  NVDA: "Nvidia",
  ORCL: "Oracle_Corporation",
  PEP: "PepsiCo",
  PFE: "Pfizer",
  PG: "Procter_%26_Gamble",
  PLD: "Prologis",
  QCOM: "Qualcomm",
  SBUX: "Starbucks",
  T: "AT%26T",
  TMO: "Thermo_Fisher_Scientific",
  TSLA: "Tesla,_Inc.",
  UNH: "UnitedHealth_Group",
  UPS: "United_Parcel_Service",
  V: "Visa_Inc.",
  VZ: "Verizon",
  WFC: "Wells_Fargo",
  WMT: "Walmart",
  XOM: "ExxonMobil",
};

export const WIKIPEDIA_ATTENTION_VERSION = "altdata.wiki_attention.robust.v0.2";
